// Generated by scripts/build_street_heirs.py. Do not edit by hand.

export type StreetHeirsTrait = { id: string; name: string; image: string; weight: number; placement?: "behind-character" | "foreground" };
export type StreetHeirsCategoryId = "atmosphere" | "complexion" | "tailoring" | "coiffure" | "visage" | "cadence" | "adornment" | "signal";
export type StreetHeirsTraitCategory = { id: StreetHeirsCategoryId; label: string; optional: false; traits: StreetHeirsTrait[] };
export const STREET_HEIRS_ART_VERSION = "street-heirs-v1";
export const streetHeirsStack = ["atmosphere", "tailoring", "complexion", "coiffure", "visage", "cadence", "adornment", "signal"] as const;
export const streetHeirsBackSignals = ["double-exposure", "offset-halo", "orbit-lines", "prism-slice", "sound-wave", "type-bars"] as const;
export const streetHeirsTraitCategories: StreetHeirsTraitCategory[] = [
  { id: "atmosphere", label: "Atmosphere", optional: false, traits: [
    { id: "midnight-grid", name: "Midnight Grid", image: "/street-heirs-traits/atmosphere/midnight-grid.png", weight: 12 },
    { id: "cobalt-sun", name: "Cobalt Sun", image: "/street-heirs-traits/atmosphere/cobalt-sun.png", weight: 13 },
    { id: "amber-blocks", name: "Amber Blocks", image: "/street-heirs-traits/atmosphere/amber-blocks.png", weight: 13 },
    { id: "jade-arc", name: "Jade Arc", image: "/street-heirs-traits/atmosphere/jade-arc.png", weight: 13 },
    { id: "violet-broadcast", name: "Violet Broadcast", image: "/street-heirs-traits/atmosphere/violet-broadcast.png", weight: 12 },
    { id: "crimson-check", name: "Crimson Check", image: "/street-heirs-traits/atmosphere/crimson-check.png", weight: 12 },
    { id: "paper-blue", name: "Paper Blue", image: "/street-heirs-traits/atmosphere/paper-blue.png", weight: 13 },
    { id: "acid-window", name: "Acid Window", image: "/street-heirs-traits/atmosphere/acid-window.png", weight: 12 },
  ] },
  { id: "complexion", label: "Complexion", optional: false, traits: [
    { id: "deep-umber", name: "Deep Umber / Angular", image: "/street-heirs-traits/complexion/deep-umber.png", weight: 12 },
    { id: "mahogany", name: "Mahogany / Broad", image: "/street-heirs-traits/complexion/mahogany.png", weight: 13 },
    { id: "sienna", name: "Sienna / Soft Jaw", image: "/street-heirs-traits/complexion/sienna.png", weight: 13 },
    { id: "copper", name: "Copper / High Cheek", image: "/street-heirs-traits/complexion/copper.png", weight: 13 },
    { id: "golden-brown", name: "Golden Brown / Tapered", image: "/street-heirs-traits/complexion/golden-brown.png", weight: 13 },
    { id: "olive", name: "Olive / Square", image: "/street-heirs-traits/complexion/olive.png", weight: 12 },
    { id: "warm-beige", name: "Warm Beige / Heart", image: "/street-heirs-traits/complexion/warm-beige.png", weight: 12 },
    { id: "cool-porcelain", name: "Cool Porcelain / Long", image: "/street-heirs-traits/complexion/cool-porcelain.png", weight: 12 },
  ] },
  { id: "tailoring", label: "Tailoring", optional: false, traits: [
    { id: "signal-bomber", name: "Signal Bomber", image: "/street-heirs-traits/tailoring/signal-bomber.png", weight: 11 },
    { id: "varsity-archive", name: "Varsity Archive", image: "/street-heirs-traits/tailoring/varsity-archive.png", weight: 10 },
    { id: "heavy-hoodie", name: "Heavy Hoodie", image: "/street-heirs-traits/tailoring/heavy-hoodie.png", weight: 12 },
    { id: "workwear-blue", name: "Workwear Blue", image: "/street-heirs-traits/tailoring/workwear-blue.png", weight: 11 },
    { id: "ribbed-turtleneck", name: "Ribbed Turtleneck", image: "/street-heirs-traits/tailoring/ribbed-turtleneck.png", weight: 10 },
    { id: "patched-denim", name: "Patched Denim", image: "/street-heirs-traits/tailoring/patched-denim.png", weight: 10 },
    { id: "football-knit", name: "Football Knit", image: "/street-heirs-traits/tailoring/football-knit.png", weight: 9 },
    { id: "track-panel", name: "Track Panel", image: "/street-heirs-traits/tailoring/track-panel.png", weight: 10 },
    { id: "quilted-vest", name: "Quilted Vest", image: "/street-heirs-traits/tailoring/quilted-vest.png", weight: 9 },
    { id: "longline-coat", name: "Longline Coat", image: "/street-heirs-traits/tailoring/longline-coat.png", weight: 8 },
  ] },
  { id: "coiffure", label: "Coiffure", optional: false, traits: [
    { id: "loc-crown", name: "Loc Crown", image: "/street-heirs-traits/coiffure/loc-crown.png", weight: 11 },
    { id: "box-braids", name: "Box Braids", image: "/street-heirs-traits/coiffure/box-braids.png", weight: 10 },
    { id: "high-puff", name: "High Puff", image: "/street-heirs-traits/coiffure/high-puff.png", weight: 11 },
    { id: "sculpted-twists", name: "Sculpted Twists", image: "/street-heirs-traits/coiffure/sculpted-twists.png", weight: 10 },
    { id: "wave-crop", name: "Wave Crop", image: "/street-heirs-traits/coiffure/wave-crop.png", weight: 11 },
    { id: "temple-fade", name: "Temple Fade", image: "/street-heirs-traits/coiffure/temple-fade.png", weight: 11 },
    { id: "buzz-design", name: "Buzz Design", image: "/street-heirs-traits/coiffure/buzz-design.png", weight: 10 },
    { id: "bandana-curls", name: "Bandana Curls", image: "/street-heirs-traits/coiffure/bandana-curls.png", weight: 9 },
    { id: "beanie-coils", name: "Beanie Coils", image: "/street-heirs-traits/coiffure/beanie-coils.png", weight: 9 },
    { id: "durag-tails", name: "Durag Tails", image: "/street-heirs-traits/coiffure/durag-tails.png", weight: 8 },
  ] },
  { id: "visage", label: "Visage", optional: false, traits: [
    { id: "steady", name: "Steady", image: "/street-heirs-traits/visage/steady.png", weight: 14 },
    { id: "side-eye", name: "Side Eye", image: "/street-heirs-traits/visage/side-eye.png", weight: 13 },
    { id: "soft-blink", name: "Soft Blink", image: "/street-heirs-traits/visage/soft-blink.png", weight: 12 },
    { id: "joy-lines", name: "Joy Lines", image: "/street-heirs-traits/visage/joy-lines.png", weight: 12 },
    { id: "amber-shades", name: "Amber Shades", image: "/street-heirs-traits/visage/amber-shades.png", weight: 11 },
    { id: "clear-frames", name: "Clear Frames", image: "/street-heirs-traits/visage/clear-frames.png", weight: 11 },
    { id: "future-visor", name: "Future Visor", image: "/street-heirs-traits/visage/future-visor.png", weight: 9 },
    { id: "star-liner", name: "Star Liner", image: "/street-heirs-traits/visage/star-liner.png", weight: 8 },
  ] },
  { id: "cadence", label: "Cadence", optional: false, traits: [
    { id: "calm", name: "Calm", image: "/street-heirs-traits/cadence/calm.png", weight: 16 },
    { id: "half-smile", name: "Half Smile", image: "/street-heirs-traits/cadence/half-smile.png", weight: 15 },
    { id: "gap-grin", name: "Gap Grin", image: "/street-heirs-traits/cadence/gap-grin.png", weight: 13 },
    { id: "berry-gloss", name: "Berry Gloss", image: "/street-heirs-traits/cadence/berry-gloss.png", weight: 12 },
    { id: "silver-tooth", name: "Silver Tooth", image: "/street-heirs-traits/cadence/silver-tooth.png", weight: 11 },
    { id: "fine-mustache", name: "Fine Mustache", image: "/street-heirs-traits/cadence/fine-mustache.png", weight: 11 },
    { id: "short-beard", name: "Short Beard", image: "/street-heirs-traits/cadence/short-beard.png", weight: 12 },
    { id: "chin-stripe", name: "Chin Stripe", image: "/street-heirs-traits/cadence/chin-stripe.png", weight: 10 },
  ] },
  { id: "adornment", label: "Adornment", optional: false, traits: [
    { id: "gold-hoops", name: "Gold Hoops", image: "/street-heirs-traits/adornment/gold-hoops.png", weight: 14 },
    { id: "silver-studs", name: "Silver Studs", image: "/street-heirs-traits/adornment/silver-studs.png", weight: 14 },
    { id: "curb-chain", name: "Curb Chain", image: "/street-heirs-traits/adornment/curb-chain.png", weight: 13 },
    { id: "pearl-line", name: "Pearl Line", image: "/street-heirs-traits/adornment/pearl-line.png", weight: 11 },
    { id: "nose-ring", name: "Nose Ring", image: "/street-heirs-traits/adornment/nose-ring.png", weight: 12 },
    { id: "ear-cuff", name: "Ear Cuff", image: "/street-heirs-traits/adornment/ear-cuff.png", weight: 12 },
    { id: "studio-cans", name: "Studio Cans", image: "/street-heirs-traits/adornment/studio-cans.png", weight: 10 },
    { id: "safety-pin", name: "Safety Pin", image: "/street-heirs-traits/adornment/safety-pin.png", weight: 9 },
  ] },
  { id: "signal", label: "Signal", optional: false, traits: [
    { id: "crop-code", name: "Crop Code", image: "/street-heirs-traits/signal/crop-code.png", weight: 13, placement: "foreground" },
    { id: "offset-halo", name: "Offset Halo", image: "/street-heirs-traits/signal/offset-halo.png", weight: 12, placement: "behind-character" },
    { id: "halftone-veil", name: "Halftone Veil", image: "/street-heirs-traits/signal/halftone-veil.png", weight: 11, placement: "foreground" },
    { id: "type-bars", name: "Type Bars", image: "/street-heirs-traits/signal/type-bars.png", weight: 11, placement: "behind-character" },
    { id: "orbit-lines", name: "Orbit Lines", image: "/street-heirs-traits/signal/orbit-lines.png", weight: 11, placement: "behind-character" },
    { id: "prism-slice", name: "Prism Slice", image: "/street-heirs-traits/signal/prism-slice.png", weight: 10, placement: "behind-character" },
    { id: "sound-wave", name: "Sound Wave", image: "/street-heirs-traits/signal/sound-wave.png", weight: 10, placement: "behind-character" },
    { id: "pixel-flare", name: "Pixel Flare", image: "/street-heirs-traits/signal/pixel-flare.png", weight: 9, placement: "foreground" },
    { id: "double-exposure", name: "Double Exposure", image: "/street-heirs-traits/signal/double-exposure.png", weight: 8, placement: "behind-character" },
    { id: "corner-stamps", name: "Corner Stamps", image: "/street-heirs-traits/signal/corner-stamps.png", weight: 8, placement: "foreground" },
  ] },
];
export type StreetHeirsSelection = Record<StreetHeirsCategoryId, string>;
export const defaultStreetHeirsSelection: StreetHeirsSelection = {"atmosphere": "midnight-grid", "complexion": "deep-umber", "tailoring": "signal-bomber", "coiffure": "loc-crown", "visage": "steady", "cadence": "silver-tooth", "adornment": "gold-hoops", "signal": "offset-halo"};
export const streetHeirsIncompatiblePairs = [{"left": {"category": "coiffure", "trait": "beanie-coils"}, "right": {"category": "adornment", "trait": "studio-cans"}}, {"left": {"category": "coiffure", "trait": "durag-tails"}, "right": {"category": "adornment", "trait": "studio-cans"}}, {"left": {"category": "visage", "trait": "future-visor"}, "right": {"category": "adornment", "trait": "studio-cans"}}, {"left": {"category": "visage", "trait": "amber-shades"}, "right": {"category": "signal", "trait": "halftone-veil"}}, {"left": {"category": "tailoring", "trait": "heavy-hoodie"}, "right": {"category": "adornment", "trait": "curb-chain"}}] as const;
export function isStreetHeirsSelectionCompatible(selection: StreetHeirsSelection) {
  return !streetHeirsIncompatiblePairs.some(({ left, right }) =>
    selection[left.category] === left.trait && selection[right.category] === right.trait,
  );
}
export function streetHeirsTraitSrc(path: string) {
  return `${path}?v=${STREET_HEIRS_ART_VERSION}`;
}
function streetHeirsTrait(categoryId: StreetHeirsCategoryId, traitId: string) {
  return streetHeirsTraitCategories.find(({ id }) => id === categoryId)?.traits.find(({ id }) => id === traitId);
}
export function streetHeirsSelectionToLayers(selection: StreetHeirsSelection) {
  const behind = streetHeirsBackSignals.includes(selection.signal as (typeof streetHeirsBackSignals)[number]);
  const order: StreetHeirsCategoryId[] = behind
    ? ["atmosphere", "signal", ...streetHeirsStack.slice(1, -1)]
    : [...streetHeirsStack];
  return order.map((categoryId) => streetHeirsTrait(categoryId, selection[categoryId]))
    .filter((trait): trait is StreetHeirsTrait => Boolean(trait))
    .map((trait) => streetHeirsTraitSrc(trait.image));
}
export const streetHeirsPlannedSupply = 5555;
export const streetHeirsChain = "Robinhood Chain";
export const streetHeirsMintPrice = "0.005 ETH";
