// Generated by scripts/build_street_heirs.py. Do not edit by hand.

export const streetHeirsStack = ["atmosphere", "complexion", "tailoring", "coiffure", "visage", "cadence", "adornment", "signal"] as const;

export const streetHeirsTraits = {
  "atmosphere": [
    {
      "id": "midnight-grid",
      "name": "Midnight Grid",
      "weight": 12
    },
    {
      "id": "cobalt-sun",
      "name": "Cobalt Sun",
      "weight": 13
    },
    {
      "id": "amber-blocks",
      "name": "Amber Blocks",
      "weight": 13
    },
    {
      "id": "jade-arc",
      "name": "Jade Arc",
      "weight": 13
    },
    {
      "id": "violet-broadcast",
      "name": "Violet Broadcast",
      "weight": 12
    },
    {
      "id": "crimson-check",
      "name": "Crimson Check",
      "weight": 12
    },
    {
      "id": "paper-blue",
      "name": "Paper Blue",
      "weight": 13
    },
    {
      "id": "acid-window",
      "name": "Acid Window",
      "weight": 12
    }
  ],
  "complexion": [
    {
      "id": "deep-umber",
      "name": "Deep Umber / Angular",
      "weight": 12
    },
    {
      "id": "mahogany",
      "name": "Mahogany / Broad",
      "weight": 13
    },
    {
      "id": "sienna",
      "name": "Sienna / Soft Jaw",
      "weight": 13
    },
    {
      "id": "copper",
      "name": "Copper / High Cheek",
      "weight": 13
    },
    {
      "id": "golden-brown",
      "name": "Golden Brown / Tapered",
      "weight": 13
    },
    {
      "id": "olive",
      "name": "Olive / Square",
      "weight": 12
    },
    {
      "id": "warm-beige",
      "name": "Warm Beige / Heart",
      "weight": 12
    },
    {
      "id": "cool-porcelain",
      "name": "Cool Porcelain / Long",
      "weight": 12
    }
  ],
  "tailoring": [
    {
      "id": "signal-bomber",
      "name": "Signal Bomber",
      "weight": 11
    },
    {
      "id": "varsity-archive",
      "name": "Varsity Archive",
      "weight": 10
    },
    {
      "id": "heavy-hoodie",
      "name": "Heavy Hoodie",
      "weight": 12
    },
    {
      "id": "workwear-blue",
      "name": "Workwear Blue",
      "weight": 11
    },
    {
      "id": "ribbed-turtleneck",
      "name": "Ribbed Turtleneck",
      "weight": 10
    },
    {
      "id": "patched-denim",
      "name": "Patched Denim",
      "weight": 10
    },
    {
      "id": "football-knit",
      "name": "Football Knit",
      "weight": 9
    },
    {
      "id": "track-panel",
      "name": "Track Panel",
      "weight": 10
    },
    {
      "id": "quilted-vest",
      "name": "Quilted Vest",
      "weight": 9
    },
    {
      "id": "longline-coat",
      "name": "Longline Coat",
      "weight": 8
    }
  ],
  "coiffure": [
    {
      "id": "loc-crown",
      "name": "Loc Crown",
      "weight": 11
    },
    {
      "id": "box-braids",
      "name": "Box Braids",
      "weight": 10
    },
    {
      "id": "high-puff",
      "name": "High Puff",
      "weight": 11
    },
    {
      "id": "sculpted-twists",
      "name": "Sculpted Twists",
      "weight": 10
    },
    {
      "id": "wave-crop",
      "name": "Wave Crop",
      "weight": 11
    },
    {
      "id": "temple-fade",
      "name": "Temple Fade",
      "weight": 11
    },
    {
      "id": "buzz-design",
      "name": "Buzz Design",
      "weight": 10
    },
    {
      "id": "bandana-curls",
      "name": "Bandana Curls",
      "weight": 9
    },
    {
      "id": "beanie-coils",
      "name": "Beanie Coils",
      "weight": 9
    },
    {
      "id": "durag-tails",
      "name": "Durag Tails",
      "weight": 8
    }
  ],
  "visage": [
    {
      "id": "steady",
      "name": "Steady",
      "weight": 14
    },
    {
      "id": "side-eye",
      "name": "Side Eye",
      "weight": 13
    },
    {
      "id": "soft-blink",
      "name": "Soft Blink",
      "weight": 12
    },
    {
      "id": "joy-lines",
      "name": "Joy Lines",
      "weight": 12
    },
    {
      "id": "amber-shades",
      "name": "Amber Shades",
      "weight": 11
    },
    {
      "id": "clear-frames",
      "name": "Clear Frames",
      "weight": 11
    },
    {
      "id": "future-visor",
      "name": "Future Visor",
      "weight": 9
    },
    {
      "id": "star-liner",
      "name": "Star Liner",
      "weight": 8
    }
  ],
  "cadence": [
    {
      "id": "calm",
      "name": "Calm",
      "weight": 16
    },
    {
      "id": "half-smile",
      "name": "Half Smile",
      "weight": 15
    },
    {
      "id": "gap-grin",
      "name": "Gap Grin",
      "weight": 13
    },
    {
      "id": "berry-gloss",
      "name": "Berry Gloss",
      "weight": 12
    },
    {
      "id": "silver-tooth",
      "name": "Silver Tooth",
      "weight": 11
    },
    {
      "id": "fine-mustache",
      "name": "Fine Mustache",
      "weight": 11
    },
    {
      "id": "short-beard",
      "name": "Short Beard",
      "weight": 12
    },
    {
      "id": "chin-stripe",
      "name": "Chin Stripe",
      "weight": 10
    }
  ],
  "adornment": [
    {
      "id": "gold-hoops",
      "name": "Gold Hoops",
      "weight": 14
    },
    {
      "id": "silver-studs",
      "name": "Silver Studs",
      "weight": 14
    },
    {
      "id": "curb-chain",
      "name": "Curb Chain",
      "weight": 13
    },
    {
      "id": "pearl-line",
      "name": "Pearl Line",
      "weight": 11
    },
    {
      "id": "nose-ring",
      "name": "Nose Ring",
      "weight": 12
    },
    {
      "id": "ear-cuff",
      "name": "Ear Cuff",
      "weight": 12
    },
    {
      "id": "studio-cans",
      "name": "Studio Cans",
      "weight": 10
    },
    {
      "id": "safety-pin",
      "name": "Safety Pin",
      "weight": 9
    }
  ],
  "signal": [
    {
      "id": "crop-code",
      "name": "Crop Code",
      "weight": 13
    },
    {
      "id": "offset-halo",
      "name": "Offset Halo",
      "weight": 12
    },
    {
      "id": "halftone-veil",
      "name": "Halftone Veil",
      "weight": 11
    },
    {
      "id": "type-bars",
      "name": "Type Bars",
      "weight": 11
    },
    {
      "id": "orbit-lines",
      "name": "Orbit Lines",
      "weight": 11
    },
    {
      "id": "prism-slice",
      "name": "Prism Slice",
      "weight": 10
    },
    {
      "id": "sound-wave",
      "name": "Sound Wave",
      "weight": 10
    },
    {
      "id": "pixel-flare",
      "name": "Pixel Flare",
      "weight": 9
    },
    {
      "id": "double-exposure",
      "name": "Double Exposure",
      "weight": 8
    },
    {
      "id": "corner-stamps",
      "name": "Corner Stamps",
      "weight": 8
    }
  ]
} as const;

export const streetHeirsPlannedSupply = 5555;
export const streetHeirsChain = "Robinhood Chain";
export const streetHeirsMintPrice = "0.005 ETH";
